import { Prompt } from "next/font/google";
import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';

const prompt = Prompt({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ["latin", "thai"],
  variable: "--font-prompt",
});

export const metadata: Metadata = {
  title: "Teaching Job Thailand",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  // 1. ดึงค่า locale จาก URL
  const { locale } = await params;

  // 2. ถ้าภาษาไม่อยู่ในรายการที่กำหนด ให้ขึ้น 404
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // 3. โหลดคำแปลจากไฟล์ JSON
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${prompt.variable} antialiased font-prompt`}>
        {/* 4. ต้องครอบด้วย Provider เพื่อให้ Navbar และหน้าเพจใช้ useTranslations ได้ */}
        <NextIntlClientProvider messages={messages}>
          <Navbar />
          <main>
            {children}
          </main>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}